---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

sudo: false
dist: trusty

cache:
  yarn: true

env:
  global:
    - AFTER_SCRIPT="true"
  matrix:
    - PHANTOM=phantomjs PHANTOM_V=1.* SCRIPT="test"
    - PHANTOM=phantomjs-prebuilt PHANTOM_V=* SCRIPT="test"
    - PHANTOM=phantomjs-prebuilt PHANTOM_V=* SCRIPT="test:sauce" AFTER_SCRIPT="ember sauce:disconnect"

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPXRyZW50bXdpbGxpcwo=`
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9MjExZDUxOTAtNWQxYS00YzYzLWFhOGYtMjA1YmIzYzRlMGZmCg==`
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install $PHANTOM@$PHANTOM_V
  - node_modules/$PHANTOM/bin/phantomjs --version

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn test:node
  - yarn $SCRIPT

after_script:
  - $AFTER_SCRIPT
