---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - BEFORE_SCRIPT="true"
    - AFTER_SCRIPT="true"
  matrix:
    - SCRIPT="test"
    - SCRIPT="test:sauce" BEFORE_SCRIPT="ember sauce:connect" AFTER_SCRIPT="ember sauce:disconnect"

matrix:
  fast_finish: true

branches:
  only:
    - master

before_install:
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPXRyZW50bXdpbGxpcwo=`
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9MjExZDUxOTAtNWQxYS00YzYzLWFhOGYtMjA1YmIzYzRlMGZmCg==`
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

before_script:
  - $BEFORE_SCRIPT

script:
  - yarn test:node
  - yarn $SCRIPT

after_script:
  - $AFTER_SCRIPT
